server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/CPT202?autoReconnect=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8

mybatis:
  type-aliases-package: First.pojo
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

resources:
  static-locations: classpath:/static

logging:
  file:
    name: log/log.log
  level:
    root: info
    First: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

