server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
<<<<<<< HEAD
    password: jyp000318
    url: jdbc:mysql://localhost:3306/cpt202?autoReconnect=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8
=======
    password: 20010623
    url: jdbc:mysql://localhost:3306/firstdemo?autoReconnect=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8
>>>>>>> bd129c07d49fc01f64a8d3b1e16917fb9ecc2e6d


mybatis:
  type-aliases-package: First.pojo
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

resources:
  static-locations: classpath:/static

logging:
  file:
    name: log/log.log
  level:
    root: info
    First: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

